public virtual class NS_IntegrationUtility {
    /*Constant for declaring body*/
    public final static string BODY = 'Body';
    /*NameSpaces variables*/
    public final static string SOAP_NS = 'http://schemas.xmlsoap.org/soap/envelope/'; 
    /*NameSpaces Variables*/
    public final static string TEM = 'http://tempuri.org/';
    /*Http request postmethod value*/
    public final Static String POST_METHOD = 'POST';
    /*Http request getmethod value*/
    public final Static String GET_METHOD = 'GET';
 	/*Http request content type*/
    public final Static String CONTENT_TYPE = 'text/xml;charset=UTF-8';  
    /*Http request SuccessStatusCode*/
    public final Static Integer SuccessStatusCode = 200;
    /* Action name for Mock Response*/    
    public final static String MOCK_ACTION ='http://mockUrl.com';
}