public class NS_IntegParams {
private String userId;
private String classCode;
private String stationCode;   
private String servingRoad;
private String equipInt;
private String equipNr;
private String waybillSrNr;   
    public void setUserId(String userId){
        this.userId=userId;
    }
    public String getUserId(){
        return userId;
    }
    public void setClassCode(String classCode){
        this.classCode=classCode;
    }
    public String getClassCode(){
        return classCode;
    }
    public void setStationCode(String stationCode){
        this.stationCode=stationCode;
    }
    public String getstationCode(){
        return stationCode;
    }
    public void setServingRoad(String servingRoad){
        this.servingRoad=servingRoad;
    }
    public String getServingRoad(){
        return servingRoad;
    }
    public void setEquipInt(String equipInt){
        this.equipInt=equipInt;
    }
    public String getEquipInt(){
        return equipInt;
    }
    public void setEquipNr(String equipNr){
        this.equipNr=equipNr;
    }
    public String getEquipNr(){
        return equipNr;
    }
    public void setWaybillSrNr(String waybillSrNr){
        this.waybillSrNr=waybillSrNr;
    }
    public String getWaybillSrNr(){
        return waybillSrNr;
    }
}