@isTest
public class NS_PicklistEntryWrapper_Test {
    
    Public static testMethod void NS_PicklistEntryWrapper_Test()
    {
        NS_PicklistEntryWrapper picklist= new NS_PicklistEntryWrapper();
	    picklist.active='Active';
        picklist.defaultValue='Default';
        picklist.label='label';
        picklist.validFor='ValidFor';
        picklist.value='Value';           
            
            }
    
}