/** 
 *  Author : Accenture 
 *  Description : Test class for SaaSTabRediectCtrl
 *  Created Date : 11\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  08\06\2015        created 
 *
 */
@isTest
public class SaaSTabRediectCtrlTest
{
    static testMethod void validateredirectPage() 
    {
        SaaSTabRediectCtrl obj = new SaaSTabRediectCtrl();
        obj.redirectPage();
    } 
}