Public with sharing Class Testing_Utility_Constants{
    Public static final String RELEASENAME ='Release';
    Public Static final String BUSINESSOBJECTIVENAME = 'Business Objectives';
    Public Static final String VALUEDRIVERNAME = 'Value Drivers';
    Public Static final String TACTICSNAME = 'Tactics';
    Public Static final String KPISNAME= 'KPIS';
    Public static final string BOBJCLASSNAME = 'pipeline1';
    Public static final string VALDRIVRCLASSNAME = 'product-dept';
    Public static final string TACTICSCLASSNAME =  'rd-dept';
    Public static final string KPISCLASSNAME = 'rd-dept1';
    Public Static final string RECID = 'Id';
 }